name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

jobs:
  hcl-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2.2.3

      - name: Check if .hcl files are formated
        run: terragrunt hcl format --check

  terragrunt-validate-plan:
    runs-on: ubuntu-latest
    needs: hcl-format-check
    strategy:
      matrix:
        env:
          - dev
          - staging
          - prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2.2.3

      - name: Set up SSH for Terragrunt module pulls
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_TG_STACK }}

      - name: Install aha to convert plan output to html
        run: sudo apt-get install aha

      - name: Terragrunt stack generate, validate, and plan on ${{ matrix.env }}
        run: |
          cd live/${{ matrix.env }}
          terragrunt stack generate
          terragrunt run --all validate --no-stack-generate
          terragrunt run --all plan --no-stack-generate > prod-plan-output.txt
          cat ${{ matrix.env }}-plan-output.txt | aha --black > prod-plan-output.html

      - name: Upload plan output (prod)
        if: matrix.env == 'prod'
        id: upload_plan
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt-prod-plan
          path: live/prod/prod-plan-output.html

      - name: Comment PR
        if: matrix.env == 'prod'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :warning: **Production Plan Available**

            Download and review the [terragrunt plan output](${{ steps.upload_plan.outputs.artifact-url }}) that ran on the production environment.

            Please review the plan carefully.  
            :exclamation: **Upon merging this PR, the plan will be applied to production!**


  terratest:
    runs-on: ubuntu-latest
    needs: terragrunt-validate-plan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2.2.3

      - name: Set up Deploy Key Terragrunt module pulls
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_TG_STACK }}

      - name: Check if PR has 'run-terratest' label
        id: check_label
        run: |
          labels=$(gh pr view "$PR_NUMBER" --json labels -q '.labels[].name')
          echo "Labels on PR: $labels"
          if echo "$labels" | grep -qw "run-terratest"; then
            echo "label_present=true" >> $GITHUB_OUTPUT
          else
            echo "The 'run-terratest' label is not present on this PR. Please add this label to run infra tests."
            exit 1
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          GH_TOKEN: ${{ github.token }}

      - name: Run Terratest
        run: go test -v ./tests/... -timeout 30m